import os
from dotenv import load_dotenv

load_dotenv()


class Settings:
    ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
    ANTHROPIC_MODEL = os.getenv("ANTHROPIC_MODEL", "claude-sonnet-4-20250514")
    ANTHROPIC_DISCOVERY_MODEL = os.getenv("ANTHROPIC_DISCOVERY_MODEL", "")
    ANTHROPIC_LEAD_RESEARCH_MODEL = os.getenv("ANTHROPIC_LEAD_RESEARCH_MODEL", "")
    SALES_ENGINE_RUN_MODE = os.getenv("SALES_ENGINE_RUN_MODE", "live")
    SALES_ENGINE_TRIGGERED_BY = os.getenv("SALES_ENGINE_TRIGGERED_BY", "manual")
    OPERATOR_CONSOLE_HOST = os.getenv("OPERATOR_CONSOLE_HOST", "127.0.0.1")
    OPERATOR_CONSOLE_PORT = int(os.getenv("OPERATOR_CONSOLE_PORT", "8787"))
    DISCOVERY_SOURCES_FILE = os.getenv("DISCOVERY_SOURCES_FILE", "discovery_sources.json")
    DISCOVERY_SOURCE_MAX_ITEMS_PER_SOURCE = int(
        os.getenv("DISCOVERY_SOURCE_MAX_ITEMS_PER_SOURCE", "10")
    )
    SUPABASE_URL = os.getenv("SUPABASE_URL", "")
    SUPABASE_PUBLISHABLE_KEY = os.getenv("SUPABASE_PUBLISHABLE_KEY", "")
    DATABASE_URL = os.getenv("DATABASE_URL", "")
    NOTION_API_KEY = os.getenv("NOTION_API_KEY", "")
    NOTION_DISCOVERY_DATABASE_ID = os.getenv("NOTION_DISCOVERY_DATABASE_ID", "")
    NOTION_INTAKE_DATABASE_ID = os.getenv("NOTION_INTAKE_DATABASE_ID", "")
    NOTION_OUTREACH_QUEUE_DATABASE_ID = os.getenv(
        "NOTION_OUTREACH_QUEUE_DATABASE_ID",
        "",
    )
    NOTION_RUNS_DATABASE_ID = os.getenv("NOTION_RUNS_DATABASE_ID", "")
    NOTION_LEADS_DATABASE_ID = os.getenv("NOTION_LEADS_DATABASE_ID", "")
    NOTION_PIPELINE_DATABASE_ID = os.getenv("NOTION_PIPELINE_DATABASE_ID", "")
    NOTION_SOLUTIONS_DATABASE_ID = os.getenv("NOTION_SOLUTIONS_DATABASE_ID", "")
    NOTION_TASKS_DATABASE_ID = os.getenv("NOTION_TASKS_DATABASE_ID", "")
    NOTION_DEAL_SUPPORT_DATABASE_ID = os.getenv("NOTION_DEAL_SUPPORT_DATABASE_ID", "")
    NOTION_ACCOUNTS_DATABASE_ID = os.getenv("NOTION_ACCOUNTS_DATABASE_ID", "")
    NOTION_BUYERS_DATABASE_ID = os.getenv("NOTION_BUYERS_DATABASE_ID", "")


settings = Settings()
